---
title: Data transformation
output: bookdown::html_chapter
bibliography: references.bib
---
  
# Data transformation {#sec:dplyr}

There are three verbs for data transformation that are very useful:
  
### Filter observations

* `filter()`

### Create new variables

diamonds is x & y more useful, or aspect ratio and size? Do you want
location and time, or velocity, or acceleration? For basketball shot
data, do you want x & y or distance and angle? For colour, do you want
rgb or hcl?


* `mutate()`

### Perform group-wise summarise

* `summarise()`

(Grouped mutates and filters are also useful, but more advanced. See the window function vignette for more details. )


### Other verbs

* `rename()`

* `transmute()`

There are two other verbs that are less useful for visualisation:

* `arrange()`, that can be useful when you're looking at the data from the 
  console. It doesn't affect visualisations because ggplot2 doesn't care about 
  the order of the rows. 
  
* `select()` picks variables based on their names. Useful when you have 
  very many variables and want to focus on just a few for analysis.

There are also verbs for working with two tables at a time.


## Learning more

* The dplyr vignettes, which you can see with 
  `browseVignettes(package = "dplyr")`, go into considerably more depth into
  dplyr. There you'll learn how to also use dplyr with data frames, and how
  to work with multiple tables of data.
