# Preface

I am tremendously grateful for the success of ggplot2. It's one of the most commonly downloaded R packages and has influenced the design of graphics packages for other languages. Personally, ggplot2 has bought me many exciting opportunities to travel the world and meet interesting people. I love hearing how people are using R, and found ggplot2 useful in their work. 

Over five years since the publication of the ggplot2 book.

Vibrant community

## Major changes

Ably aided in this endeavour by Carson Sievert.

* Accompanying the book is ggplot 1.1.0, which includes a number of minor
  tweaks and improvements, and considerable improvements to the documentation. 
  Having come back to ggplot2 development after a considerable pause has
  helped me to see problems that previously escaped notice. 

* Updated syntax everywhere to be 1.1.0 compatible. Much more code is shown in 
  the book, so it's easier to use the book as a reference. The complete source 
  is also available online at <http://github.com/hadley/ggplot2-book/issues>.
  Converted to Rmarkdown, since (in my opinion), that's the best way to
  write books about R. Has a more knitr-ish sensibility - fewer floating
  figures and tables, and more inline code. This makes the layout a little
  less pretty but keeps related items closer together.

* Have worked through the complete book, focussing on features that time has 
  shown to be most useful. I've also added a number of practice exercises
  throughout the book so you can practice new techniques immediately after
  learning about them. I now have a better understand of how the pieces of
  ggplot2 fit together, so you should also find the book better organised.

* Since the first edition, a rich ecosystem of add on packages has grown
  up around ggplot2. I've added many pointers to useful packages, and 
  integrated the most useful directly into the book.
  
* I have minimised the use of `qplot()` in favour of `ggplot()`. Feedback 
  indicated that `qplot()` was a crutch: while it made simple plots a little
  easier to create, it didn't help with mastering the grammar. The intro
  chapter now uses the mpg dataset as it avoids some of the incidental 
  challenges posed by the diamonds data.

* The toolbox chapter has been overhauled to feature new geoms. I've added a
  completely new section on text, since it's important and not covered in 
  detail elsewhere. Overhauled mapping section to focus on data types and 
  give pointers on where to get more data. Model related code has moved into 
  [the modelling chapter](#cha:modelling), and annotations into 
  [the polishing chapter](#cha:polishing).

* The scales chapter has been completely rewritten. It has been reorganised to 
  focus on what you most commonly want to do when manipulating scale objects: 
  affect the appearance of the axes and legends. It also includes the many
  updates that give finer control over guide appearance.

* The data analysis chapter has been split into three pieces focussing on
  data tidying (with tidyr), data manipulation (with dplyr), and 
  visualising models (with broom).

## The future

ggplot2 is now stable, and is unlikely to change much in the future. There will be bug fixes and there may be new geoms, but the majority of functions will stay the same. 

ggplot2 was my second R package (after reshape) and I made many mistakes when designing in. It's also now quite difficult to change because so many people rely on it. Even fixing a bug can cause problems if people have figured out work arounds that fixing the bug breaks. 

The next iteration of ggplot2 is ggvis. ggvis is significantly more ambitious because it aims to provide a grammar of _interactive_ graphics. ggvis is still young, and lacks many of the features of ggplot2 (most notably it currently lacks facetting and has no way to make static graphics), but over the coming years the goal is for ggvis to better than ggplot2 along most axes.

The syntax of ggvis is a little different to ggplot2 - we've made some changes to clarify confusions that many people have when learning. This means you won't be able to trivially convert your ggplot2 plots to ggvis. But if you've mastered ggplot2, you'll find your skills transfer very well to ggvis and once you've struggled with the new syntax it will feel more natural. The important skills you learn when mastering ggplot2 are not the trivialities of specifying a plot with code, but the much harder challenge of thinking about how to turn data into something visual. 

Winston's book.