---
title: "Carson's Notes"
output: html_document
---

### Hadley TO-DO:

* Address concerns raised by Ian Lyttle under notes/ian.Rmd. I managed to fix some other comments he sent, but left ones that need your input.
* Perhaps we could add a section that demonstrates how to implement your own geom? Toby Dylan Hocking has a [nice little write-up](http://directlabels.r-forge.r-project.org/extending-ggplot2.html) on this path and indicated he may be willing to contribute to this portion if we decide to include it.
* [This works now](https://github.com/hadley/ggplot2-book/blob/ad2116e4c970b090b7b98845415293f7585e89b0/scales.Rnw#L58-L70). That is, you don't have to add `scale_x_discrete()`, do you want to remove this part?
* `set_default_scale` no longer exists so we should update [this line](https://github.com/hadley/ggplot2-book/blob/ad2116e4c970b090b7b98845415293f7585e89b0/scales.Rnw#L56) and [this section](https://github.com/hadley/ggplot2-book/blob/ad2116e4c970b090b7b98845415293f7585e89b0/polishing.Rnw#L222) accordingly.
* `scale_brewer` no longer exists. What would you suggest to change [this part]() to?
*

### Questions for Hadley:

* When to use ggplot2 over ggplot?
* Do you care about reproducility of the colour wheel? I wasn't quite sure of the best way to generate this ['selected' data](https://github.com/hadley/ggplot2-book/blob/f32128c2a09e4ae69be7b0ae414c2a1694710fa4/colour-wheel.r#L22)

### Carson TO-DO:

* When referring to the ggplot2 'system', don't use code markup.
* Fix references placement.
* How to do proper line-wrapping in tables?
* How to get xtable to respect control sequences?